import type { BranchSummary, ReviewWithBranch, SyncLog } from "./types";

const now = Date.now();
const daysAgo = (d: number) => Math.floor((now - d * 24 * 60 * 60 * 1000) / 1000);

export const mockBranches: BranchSummary[] = [
  {
    id: "b-cbr",
    branch_name: "FTL GYM Cibubur",
    branch_code: "CBR",
    region: "Jabodetabek",
    city: "Jakarta Timur",
    google_rating: 4.6,
    total_reviews: 842,
    google_place_id: "MOCK_PLACE_ID",
    latitude:-6.37,
    longitude: 106.88,
    photo_uri: null,
    photo_attribution: null,
    photo_synced_at: null,
    last_synced_at: new Date(now - 3 * 3600 * 1000).toISOString(),
    stored_reviews: 5,
    negative_reviews: 0,
    neutral_reviews: 1,
    positive_reviews: 4,
    avg_stored_rating: 4.4,
  },
  {
    id: "b-kpg",
    branch_name: "FTL GYM Kelapa Gading",
    branch_code: "KPG",
    region: "Jabodetabek",
    city: "Jakarta Utara",
    google_rating: 4.4,
    total_reviews: 611,
    google_place_id: "MOCK_PLACE_ID",
    latitude:-6.158,
    longitude: 106.905,
    photo_uri: null,
    photo_attribution: null,
    photo_synced_at: null,
    last_synced_at: new Date(now - 3 * 3600 * 1000).toISOString(),
    stored_reviews: 5,
    negative_reviews: 1,
    neutral_reviews: 0,
    positive_reviews: 4,
    avg_stored_rating: 4.2,
  },
  {
    id: "b-pik",
    branch_name: "FTL GYM PIK",
    branch_code: "PIK",
    region: "Jabodetabek",
    city: "Jakarta Utara",
    google_rating: 4.7,
    total_reviews: 1204,
    google_place_id: "MOCK_PLACE_ID",
    latitude:-6.11,
    longitude: 106.74,
    photo_uri: null,
    photo_attribution: null,
    photo_synced_at: null,
    last_synced_at: new Date(now - 3 * 3600 * 1000).toISOString(),
    stored_reviews: 5,
    negative_reviews: 0,
    neutral_reviews: 0,
    positive_reviews: 5,
    avg_stored_rating: 4.8,
  },
  {
    id: "b-bsd",
    branch_name: "FTL GYM BSD",
    branch_code: "BSD",
    region: "Jabodetabek",
    city: "Tangerang Selatan",
    google_rating: 4.3,
    total_reviews: 498,
    google_place_id: "MOCK_PLACE_ID",
    latitude:-6.302,
    longitude: 106.653,
    photo_uri: null,
    photo_attribution: null,
    photo_synced_at: null,
    last_synced_at: new Date(now - 3 * 3600 * 1000).toISOString(),
    stored_reviews: 5,
    negative_reviews: 2,
    neutral_reviews: 1,
    positive_reviews: 2,
    avg_stored_rating: 3.4,
  },
  {
    id: "b-bks",
    branch_name: "FTL GYM Bekasi",
    branch_code: "BKS",
    region: "Jabodetabek",
    city: "Bekasi",
    google_rating: 4.5,
    total_reviews: 387,
    google_place_id: "MOCK_PLACE_ID",
    latitude:-6.2383,
    longitude: 106.9756,
    photo_uri: null,
    photo_attribution: null,
    photo_synced_at: null,
    last_synced_at: new Date(now - 3 * 3600 * 1000).toISOString(),
    stored_reviews: 5,
    negative_reviews: 0,
    neutral_reviews: 1,
    positive_reviews: 4,
    avg_stored_rating: 4.4,
  },
  {
    id: "b-dpk",
    branch_name: "FTL GYM Depok",
    branch_code: "DPK",
    region: "Jabodetabek",
    city: "Depok",
    google_rating: 4.2,
    total_reviews: 256,
    google_place_id: "MOCK_PLACE_ID",
    latitude:-6.4025,
    longitude: 106.7942,
    photo_uri: null,
    photo_attribution: null,
    photo_synced_at: null,
    last_synced_at: new Date(now - 3 * 3600 * 1000).toISOString(),
    stored_reviews: 5,
    negative_reviews: 1,
    neutral_reviews: 1,
    positive_reviews: 3,
    avg_stored_rating: 3.8,
  },
  {
    id: "b-blk",
    branch_name: "FTL GYM Bali Kuta",
    branch_code: "BLK",
    region: "Bali",
    city: "Badung",
    google_rating: 4.8,
    total_reviews: 743,
    google_place_id: "MOCK_PLACE_ID",
    latitude:-8.718,
    longitude: 115.171,
    photo_uri: null,
    photo_attribution: null,
    photo_synced_at: null,
    last_synced_at: new Date(now - 3 * 3600 * 1000).toISOString(),
    stored_reviews: 5,
    negative_reviews: 0,
    neutral_reviews: 0,
    positive_reviews: 5,
    avg_stored_rating: 4.8,
  },
  {
    id: "b-bls",
    branch_name: "FTL GYM Bali Seminyak",
    branch_code: "BLS",
    region: "Bali",
    city: "Badung",
    google_rating: 4.6,
    total_reviews: 521,
    google_place_id: "MOCK_PLACE_ID",
    latitude:-8.69,
    longitude: 115.16,
    photo_uri: null,
    photo_attribution: null,
    photo_synced_at: null,
    last_synced_at: new Date(now - 3 * 3600 * 1000).toISOString(),
    stored_reviews: 5,
    negative_reviews: 0,
    neutral_reviews: 1,
    positive_reviews: 4,
    avg_stored_rating: 4.4,
  },
  {
    id: "b-sby",
    branch_name: "FTL GYM Surabaya",
    branch_code: "SBY",
    region: "Surabaya",
    city: "Surabaya",
    google_rating: 4.4,
    total_reviews: 329,
    google_place_id: "MOCK_PLACE_ID",
    latitude:-7.2575,
    longitude: 112.7521,
    photo_uri: null,
    photo_attribution: null,
    photo_synced_at: null,
    last_synced_at: new Date(now - 3 * 3600 * 1000).toISOString(),
    stored_reviews: 5,
    negative_reviews: 1,
    neutral_reviews: 0,
    positive_reviews: 4,
    avg_stored_rating: 4.2,
  },
  {
    id: "b-bdg",
    branch_name: "FTL GYM Bandung",
    branch_code: "BDG",
    region: "Bandung",
    city: "Bandung",
    google_rating: 4.5,
    total_reviews: 412,
    google_place_id: "MOCK_PLACE_ID",
    latitude:-6.9175,
    longitude: 107.6191,
    photo_uri: null,
    photo_attribution: null,
    photo_synced_at: null,
    last_synced_at: new Date(now - 3 * 3600 * 1000).toISOString(),
    stored_reviews: 5,
    negative_reviews: 0,
    neutral_reviews: 1,
    positive_reviews: 4,
    avg_stored_rating: 4.4,
  },
];

const reviewSeeds: Array<{
  branch: string;
  author: string;
  rating: number;
  text: string;
  rel: string;
  days: number;
  responded?: boolean;
  flagged?: boolean;
}> = [
  { branch: "b-cbr", author: "Dian Puspita", rating: 5, text: "Alatnya lengkap banget, coach-nya ramah. Sauna-nya bonus yang worth it!", rel: "2 hari yang lalu", days: 2, responded: true },
  { branch: "b-cbr", author: "Rudi Hartono", rating: 4, text: "Kelas pilatesnya solid. Parkir kadang penuh tapi overall mantap.", rel: "1 minggu yang lalu", days: 7 },
  { branch: "b-cbr", author: "Amanda S.", rating: 5, text: "Best gym di Cibubur. Instructor-nya well-certified.", rel: "2 minggu yang lalu", days: 14, responded: true },
  { branch: "b-cbr", author: "Budi Santosa", rating: 3, text: "Lumayan. AC di studio pilates kadang kurang dingin.", rel: "3 minggu yang lalu", days: 21, flagged: true },
  { branch: "b-cbr", author: "Nina W.", rating: 5, text: "Reformer & Megacore class-nya favorit banget. Worth every penny.", rel: "1 bulan yang lalu", days: 30 },

  { branch: "b-kpg", author: "Sinta Dewi", rating: 2, text: "Staff front desk kurang responsif waktu saya tanya info membership. Lama banget nunggu.", rel: "3 hari yang lalu", days: 3, flagged: true },
  { branch: "b-kpg", author: "Adi Nugroho", rating: 5, text: "Alatnya selalu bersih. Recovery area jadi tempat favorit saya.", rel: "1 minggu yang lalu", days: 7, responded: true },
  { branch: "b-kpg", author: "Maya L.", rating: 4, text: "Kelas group pilates fun. Instruktur Mba Rina recommended!", rel: "2 minggu yang lalu", days: 14 },
  { branch: "b-kpg", author: "Fauzi R.", rating: 5, text: "24 jam! Bisa gym jam 3 pagi itu life-changing buat jadwal saya.", rel: "3 minggu yang lalu", days: 21 },
  { branch: "b-kpg", author: "Citra A.", rating: 4, text: "Overall bagus. Towel service-nya plus besar.", rel: "1 bulan yang lalu", days: 30 },

  { branch: "b-pik", author: "Vincent Tanoto", rating: 5, text: "Studio paling bagus di area PIK. View-nya juga enak pas stretching.", rel: "1 hari yang lalu", days: 1, responded: true },
  { branch: "b-pik", author: "Grace L.", rating: 5, text: "EXBODY assessment-nya detail banget. Langsung tau mesti fokus ke mana.", rel: "4 hari yang lalu", days: 4 },
  { branch: "b-pik", author: "Kenji P.", rating: 5, text: "Trainer PT-nya pro. Progress saya 3 bulan keliatan signifikan.", rel: "1 minggu yang lalu", days: 7, responded: true },
  { branch: "b-pik", author: "Olivia R.", rating: 4, text: "Suka kelas Megacore-nya, unik ga ada di gym lain. Cuma slot suka cepet penuh.", rel: "2 minggu yang lalu", days: 14 },
  { branch: "b-pik", author: "Devan K.", rating: 5, text: "All-in-one membership worth it. Gym + pilates + sauna satu tempat.", rel: "3 minggu yang lalu", days: 21 },

  { branch: "b-bsd", author: "Hendra W.", rating: 1, text: "Billing issue 2 bulan belum kelar. Sudah email, sudah WA, belum ada solusi konkret. Kecewa.", rel: "1 hari yang lalu", days: 1, flagged: true },
  { branch: "b-bsd", author: "Lia M.", rating: 2, text: "AC di area free weights rusak. Udah 2 minggu belum diperbaiki.", rel: "5 hari yang lalu", days: 5, flagged: true },
  { branch: "b-bsd", author: "Rizky P.", rating: 3, text: "Alat lengkap tapi kebersihan toilet masih bisa ditingkatkan.", rel: "1 minggu yang lalu", days: 7 },
  { branch: "b-bsd", author: "Tania F.", rating: 5, text: "Kelas pilates-nya bagus. Coach Vina sabar ngajarin beginner.", rel: "2 minggu yang lalu", days: 14, responded: true },
  { branch: "b-bsd", author: "Agus H.", rating: 4, text: "Fasilitas oke, tapi crowd peak hour (6-8 malam) rame banget.", rel: "3 minggu yang lalu", days: 21 },

  { branch: "b-bks", author: "Rina P.", rating: 5, text: "Terbaik di Bekasi. Trainer-nya ramah dan knowledgeable.", rel: "2 hari yang lalu", days: 2, responded: true },
  { branch: "b-bks", author: "Fajar B.", rating: 4, text: "Harga membership masuk akal untuk fasilitas yg dapet.", rel: "1 minggu yang lalu", days: 7 },
  { branch: "b-bks", author: "Sari W.", rating: 3, text: "Kelas pilates slot-nya suka rebutan. Perlu sistem booking yg lebih advance.", rel: "2 minggu yang lalu", days: 14 },
  { branch: "b-bks", author: "Doni S.", rating: 5, text: "Sauna-nya clean. Recovery room jadi alasan utama saya balik.", rel: "3 minggu yang lalu", days: 21 },
  { branch: "b-bks", author: "Yuni K.", rating: 4, text: "Duo Pass-nya deal bagus. Datang bareng suami jadi hemat.", rel: "1 bulan yang lalu", days: 30 },

  { branch: "b-dpk", author: "Arief R.", rating: 2, text: "Locker sempit. Handuk kadang abis pas jam sibuk.", rel: "4 hari yang lalu", days: 4, flagged: true },
  { branch: "b-dpk", author: "Mega S.", rating: 4, text: "Suasana nyaman, ga crowded kayak gym lain di Depok.", rel: "1 minggu yang lalu", days: 7 },
  { branch: "b-dpk", author: "Yoga P.", rating: 5, text: "PT-nya bagus. Program 3 bulan saya turun 8kg.", rel: "2 minggu yang lalu", days: 14, responded: true },
  { branch: "b-dpk", author: "Laras W.", rating: 3, text: "Lumayan, tapi pilates class-nya masih terbatas jadwalnya dibanding cabang lain.", rel: "3 minggu yang lalu", days: 21 },
  { branch: "b-dpk", author: "Bagus T.", rating: 5, text: "Harga terjangkau, fasilitas premium. Win-win.", rel: "1 bulan yang lalu", days: 30 },

  { branch: "b-blk", author: "Putu A.", rating: 5, text: "Best gym experience in Kuta. Foreign-friendly staff.", rel: "3 hari yang lalu", days: 3, responded: true },
  { branch: "b-blk", author: "Sarah M.", rating: 5, text: "Great equipment, clean facilities. Day pass option is perfect for travelers.", rel: "1 minggu yang lalu", days: 7 },
  { branch: "b-blk", author: "Gede W.", rating: 5, text: "Sauna view-nya santai. Recovery-nya the best.", rel: "2 minggu yang lalu", days: 14 },
  { branch: "b-blk", author: "Wayan K.", rating: 4, text: "Lengkap. Saran: tambahin kelas yoga outdoor.", rel: "3 minggu yang lalu", days: 21 },
  { branch: "b-blk", author: "Emma L.", rating: 5, text: "Loved the pilates class. Instructor spoke English well.", rel: "1 bulan yang lalu", days: 30, responded: true },

  { branch: "b-bls", author: "Made S.", rating: 5, text: "Seminyak branch-nya bagus banget. Clean dan well-designed.", rel: "2 hari yang lalu", days: 2 },
  { branch: "b-bls", author: "John D.", rating: 3, text: "Decent gym but peak hours get crowded. Machines need queue.", rel: "1 minggu yang lalu", days: 7, flagged: true },
  { branch: "b-bls", author: "Kadek A.", rating: 5, text: "Reformer pilates-nya top. Coach internationally certified keliatan.", rel: "2 minggu yang lalu", days: 14, responded: true },
  { branch: "b-bls", author: "Nyoman P.", rating: 4, text: "Fasilitas lengkap. Parkir agak susah kalo weekend.", rel: "3 minggu yang lalu", days: 21 },
  { branch: "b-bls", author: "Lisa K.", rating: 5, text: "Great atmosphere. Staff-nya welcoming ke turis dan lokal.", rel: "1 bulan yang lalu", days: 30 },

  { branch: "b-sby", author: "Surya H.", rating: 5, text: "Gym terbesar di Surabaya. Alatnya lengkap, coach pro.", rel: "3 hari yang lalu", days: 3, responded: true },
  { branch: "b-sby", author: "Melati P.", rating: 4, text: "Suka pilates class-nya. Instruktur baik ngajarin pemula.", rel: "1 minggu yang lalu", days: 7 },
  { branch: "b-sby", author: "Hadi S.", rating: 2, text: "Reservation system-nya masih suka error. Sering dobel-book.", rel: "2 minggu yang lalu", days: 14, flagged: true },
  { branch: "b-sby", author: "Indah R.", rating: 5, text: "FMBG bikin saya berani coba. Ternyata ga pernah pake, karna udah puas.", rel: "3 minggu yang lalu", days: 21 },
  { branch: "b-sby", author: "Eko W.", rating: 5, text: "Sauna + recovery room = game changer after leg day.", rel: "1 bulan yang lalu", days: 30 },

  { branch: "b-bdg", author: "Dewi K.", rating: 5, text: "Studio pilates-nya bersih. Alat lengkap Reformer, Chair, Ladder Barrel, semua ada.", rel: "2 hari yang lalu", days: 2, responded: true },
  { branch: "b-bdg", author: "Rahmat A.", rating: 4, text: "Fasilitas OK. Sedikit ramai di weekend.", rel: "1 minggu yang lalu", days: 7 },
  { branch: "b-bdg", author: "Yani P.", rating: 5, text: "Worth it jauh-jauh dari Dago. Coach-nya pro.", rel: "2 minggu yang lalu", days: 14 },
  { branch: "b-bdg", author: "Teguh S.", rating: 3, text: "Lumayan. Butuh kelas tambahan di jam pagi.", rel: "3 minggu yang lalu", days: 21 },
  { branch: "b-bdg", author: "Nadia F.", rating: 5, text: "Bandung's hidden gem. All-in-one membership-nya super value.", rel: "1 bulan yang lalu", days: 30, responded: true },
];

export const mockReviews: ReviewWithBranch[] = reviewSeeds.map((r, i) => {
  const branch = mockBranches.find((b) => b.id === r.branch)!;
  const sentiment = r.rating >= 4 ? "positive" : r.rating === 3 ? "neutral" : "negative";
  return {
    id: `r-${i}`,
    branch_id: r.branch,
    google_review_id: `grev_${i}`,
    author_name: r.author,
    author_photo_url: null,
    rating: r.rating,
    review_text: r.text,
    language: "id",
    relative_time: r.rel,
    review_time: daysAgo(r.days),
    is_responded: r.responded ?? false,
    response_text: r.responded ? "Terima kasih atas review-nya! 🙏" : null,
    sentiment,
    flagged: r.flagged ?? false,
    notes: null,
    first_seen_at: new Date(now - r.days * 24 * 3600 * 1000).toISOString(),
    branch_name: branch.branch_name,
    branch_code: branch.branch_code,
    region: branch.region,
    google_place_id: branch.google_place_id,
  };
});

export const mockSyncLogs: SyncLog[] = [
  {
    id: "s-1",
    started_at: new Date(now - 3 * 3600 * 1000).toISOString(),
    finished_at: new Date(now - 3 * 3600 * 1000 + 45000).toISOString(),
    branches_processed: 10,
    new_reviews_found: 3,
    errors: [],
    status: "completed",
  },
  {
    id: "s-2",
    started_at: new Date(now - 27 * 3600 * 1000).toISOString(),
    finished_at: new Date(now - 27 * 3600 * 1000 + 52000).toISOString(),
    branches_processed: 10,
    new_reviews_found: 7,
    errors: [],
    status: "completed",
  },
  {
    id: "s-3",
    started_at: new Date(now - 51 * 3600 * 1000).toISOString(),
    finished_at: new Date(now - 51 * 3600 * 1000 + 48000).toISOString(),
    branches_processed: 10,
    new_reviews_found: 5,
    errors: [],
    status: "completed",
  },
];
